config/routes.rb
Rails.application.routes.draw do

  resources :posts  do
  	resources :comments
  end


  #we want posts to be the root of the application, so posts index action
  root "posts#index"

  #The full resources are not needed, like update, delete, etc, so we do not have to use resources as above.
  get '/about', to: 'pages#about'
  #This allows you to go to /about instead of /pages/about

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence:true, length: {minimum: 5}
	validates :body, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		#creates a create action
	@post = Post.find(params[:post_id])
	@comment = @post.comments.create(params[:comment].permit(:name, :body))

	redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	#making an about page
	def about 
	end
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		#This will show all posts in descending order
		@posts = Post.all.order('created_at DESC')
	end

	def new
		@post = Post.new
	end

	#to save posts we need to create a create posts
	def create
		@post = Post.new(post_params)
		#Note: rails 4 requires you to explicitly say what parameters you are going to allow
		if @post.save
			redirect_to @post
		else
			#render prevents using redirect so you don't lose what is being validated
			render 'new'
		end
	end

	#we are defining @post
	def show
		@post = Post.find(params[:id])
	end

	def edit
		#post from the ide
		@post = Post.find(params[:id])
	end

	def update
		#find the post by id
		@post = Post.find(params[:id])

		#if  permit the title and body
		if @post.update(params[:post].permit(:title, :body))
			redirect_to	@post
		else
			render 'edit'
		end

	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		#redirects to the index
		redirect_to root_path
	end

	private
		def post_params
			params.require(:post).permit(:title, :body)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong>	</p>
		<p class="comment_body"><%= comment.body %>	</p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %>	</p>
	</div>
	<p><%= link_to 'Delete', [comment.post, comment],
				method: :delete,
				class: "button",
				data: { confirm: "Are you sure"}
		%>
	</p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
 	<p>
 		<%= f.label :name %><br>
 		<%= f.text_field :name %>
 	</p>
 	<p>
 		<%= f.label :body %><br>
 		<%= f.text_area :body %>
 	</p>
 	<p>
 		<%= f.submit %>
 	</p>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <% stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raileway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% #Going to create a side bar %>
<% #Side bar has logo container, with a link to the root path, that wraps around an image tag that uses logo.svg %>
<div id="sidebar">
	<div id="logo">
		<%= link_to root_path do %>
			<%= image_tag "logo.png" %>
		<% end %>
	</div>
	<ul>
		<li class="category">Website</li>
		<li><%= link_to "Blog", root_path %></li>
		<li><%= link_to "About", about_path %></li>
	</ul>
	<ul>
		<li class="category">Website</li>
		<li><a href="http://danesposito.com">Facebook</a></li>
		<li><a href="http://danesposito.com">Instagram</a></li>
		<li><a href="http://danesposito.com" >Github</a></li>
		<li><a href="http://danesposito.com">Email</a></li>
	</ul>

	<p class="sign_in">Admin Login</p>
</div>

<div id="main_content">
	<div id="header">
	<% if current_page?(root_path) %>
		<p>All Posts</p>
	<% elsif current_page?(about_path) %>
		<p>About</p>
	<% else %>
		<p><%= link_to "Back to All Posts", root_path %></p>
	<% end %>

		<div class="buttons">
		<button class="button"><%= link_to "New Post", new_post_path %></button>
		<button class="button">Log Out</button>
			
		</button>
		</div>
	</div>
	<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert") %>
	<% end %>
	<%= yield %>
</div>


</body>
</html>

app/views/pages/about.html.erb
<h1>Hey</h1>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<%#Changed above to @post becuase rails is smart enough to know the difference%>
	<%#If errors, in a div, h2 there are a x number of errors, then lists it out. Pluralizes makes plural, make a list of all the erros%>
	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving.</h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>

			</ul>
		</div>
	<% end %>
	<p>
		<%= f.label :title %><br>
		<%=f.text_field :title%>
	</p>
	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body%>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
<h1>Edit Post</h1>
<%#calls form partial %>
<%= render 'form' %>

</div>

app/views/posts/index.html.erb
<%#for each post, show title that links to the post, displays the date created %>
<% @posts.each do |post| %>
	<div class="post_wrapper">
		<h2 class="title">
			<%= link_to post.title, post %>
		</h2>
		<p class="date">
			<%= post.created_at.strftime("%B, %d, %Y")%>
		</p>
	</div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
<h1>New Post</h1>


<%= form_for :post, url:posts_path do |f| %>
	<%#If errors, in a div, h2 there are a x number of errors, then lists it out. Pluralizes makes plural, make a list of all the erros%>
	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving.</h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>

			</ul>
		</div>
	<% end %>
	<p>
		<%= f.label :title %><br>
		<%=f.text_field :title%>
	</p>
	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body%>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
<h1 class="title">
	<% #returns the title of the post %>
	<%= @post.title %>
</h1>

<p class="date">
	<% #returns the time in terms of time passed, that the post was created %>
	Submitted <%= time_ago_in_words(@post.created_at) %> Ago
	| <%= link_to 'Edit', edit_post_path(@post) %>
	| <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?'} %>  

</p>

<p class="body">
	<% #returns body of the post %>
	<%= @post.body %>
</p>
<div id="comments">
	<h2><%= @post.comments.count %> Comments</h2>
	<%= render @post.comments %>
	<h3>Add a Comment</h3>
	<%= render "comments/form" %> 
</div>
</div>